use crate::app_core::{
    APP_CORE_API_VERSION, REQUIRED_MAIN_HOST_EXECUTION_PLAN_KINDS,
    REQUIRED_NATIVE_CONTROL_MAPPER_OPERATIONS, REQUIRED_NATIVE_DIALOG_HOST_OPERATIONS,
    REQUIRED_NATIVE_EDIT_TEXT_DIALOG_HOST_OPERATIONS, REQUIRED_NATIVE_FILE_DIALOG_HOST_OPERATIONS,
    REQUIRED_NATIVE_IME_HOST_OPERATIONS, REQUIRED_NATIVE_MAIL_MERGE_WINDOW_HOST_OPERATIONS,
    REQUIRED_NATIVE_MAIN_SEARCH_CONTROL_HOST_OPERATIONS,
    REQUIRED_NATIVE_MAIN_WINDOW_HOST_OPERATIONS, REQUIRED_NATIVE_PASTE_TARGET_HOST_OPERATIONS,
    REQUIRED_NATIVE_POPUP_MENU_HOST_OPERATIONS, REQUIRED_NATIVE_SETTINGS_DROPDOWN_HOST_OPERATIONS,
    REQUIRED_NATIVE_SETTINGS_WINDOW_HOST_OPERATIONS, REQUIRED_NATIVE_SHELL_OPEN_HOST_OPERATIONS,
    REQUIRED_NATIVE_STYLE_HOST_OPERATIONS, REQUIRED_NATIVE_TEXT_CARET_HOST_OPERATIONS,
    REQUIRED_NATIVE_TEXT_INPUT_DIALOG_HOST_OPERATIONS,
    REQUIRED_NATIVE_TRANSIENT_WINDOW_HOST_OPERATIONS,
    REQUIRED_NATIVE_WINDOW_IDENTITY_HOST_OPERATIONS, REQUIRED_RENDERER_HOST_OPERATIONS,
    REQUIRED_SETTINGS_CONTROL_HOST_OPERATIONS, REQUIRED_STATUS_ITEM_HOST_OPERATIONS,
    REQUIRED_TEXT_LAYOUT_HOST_OPERATIONS, REQUIRED_UI_HOST_SURFACES, SHARED_NON_HOST_UI_PROTOCOLS,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum LinuxNativeBackend {
    Gtk4Libadwaita,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct LinuxHostContractSummary {
    pub(crate) api_major: u16,
    pub(crate) api_minor: u16,
    pub(crate) surfaces: usize,
    pub(crate) main_execution_plans: usize,
    pub(crate) native_style_operations: usize,
    pub(crate) native_control_mapper_operations: usize,
    pub(crate) text_layout_operations: usize,
    pub(crate) status_item_operations: usize,
    pub(crate) popup_menu_operations: usize,
    pub(crate) transient_window_operations: usize,
    pub(crate) ime_operations: usize,
    pub(crate) dialog_operations: usize,
    pub(crate) shell_open_operations: usize,
    pub(crate) window_identity_operations: usize,
    pub(crate) paste_target_operations: usize,
    pub(crate) text_caret_operations: usize,
    pub(crate) file_dialog_operations: usize,
    pub(crate) text_input_dialog_operations: usize,
    pub(crate) edit_text_dialog_operations: usize,
    pub(crate) mail_merge_window_operations: usize,
    pub(crate) renderer_operations: usize,
    pub(crate) main_window_operations: usize,
    pub(crate) main_search_operations: usize,
    pub(crate) settings_window_operations: usize,
    pub(crate) settings_control_operations: usize,
    pub(crate) settings_dropdown_operations: usize,
    pub(crate) shared_non_host_protocols: usize,
    pub(crate) backend: LinuxNativeBackend,
}

pub(crate) fn linux_host_contract_summary() -> LinuxHostContractSummary {
    LinuxHostContractSummary {
        api_major: APP_CORE_API_VERSION.major,
        api_minor: APP_CORE_API_VERSION.minor,
        surfaces: REQUIRED_UI_HOST_SURFACES.len(),
        main_execution_plans: REQUIRED_MAIN_HOST_EXECUTION_PLAN_KINDS.len(),
        native_style_operations: REQUIRED_NATIVE_STYLE_HOST_OPERATIONS.len(),
        native_control_mapper_operations: REQUIRED_NATIVE_CONTROL_MAPPER_OPERATIONS.len(),
        text_layout_operations: REQUIRED_TEXT_LAYOUT_HOST_OPERATIONS.len(),
        status_item_operations: REQUIRED_STATUS_ITEM_HOST_OPERATIONS.len(),
        popup_menu_operations: REQUIRED_NATIVE_POPUP_MENU_HOST_OPERATIONS.len(),
        transient_window_operations: REQUIRED_NATIVE_TRANSIENT_WINDOW_HOST_OPERATIONS.len(),
        ime_operations: REQUIRED_NATIVE_IME_HOST_OPERATIONS.len(),
        dialog_operations: REQUIRED_NATIVE_DIALOG_HOST_OPERATIONS.len(),
        shell_open_operations: REQUIRED_NATIVE_SHELL_OPEN_HOST_OPERATIONS.len(),
        window_identity_operations: REQUIRED_NATIVE_WINDOW_IDENTITY_HOST_OPERATIONS.len(),
        paste_target_operations: REQUIRED_NATIVE_PASTE_TARGET_HOST_OPERATIONS.len(),
        text_caret_operations: REQUIRED_NATIVE_TEXT_CARET_HOST_OPERATIONS.len(),
        file_dialog_operations: REQUIRED_NATIVE_FILE_DIALOG_HOST_OPERATIONS.len(),
        text_input_dialog_operations: REQUIRED_NATIVE_TEXT_INPUT_DIALOG_HOST_OPERATIONS.len(),
        edit_text_dialog_operations: REQUIRED_NATIVE_EDIT_TEXT_DIALOG_HOST_OPERATIONS.len(),
        mail_merge_window_operations: REQUIRED_NATIVE_MAIL_MERGE_WINDOW_HOST_OPERATIONS.len(),
        renderer_operations: REQUIRED_RENDERER_HOST_OPERATIONS.len(),
        main_window_operations: REQUIRED_NATIVE_MAIN_WINDOW_HOST_OPERATIONS.len(),
        main_search_operations: REQUIRED_NATIVE_MAIN_SEARCH_CONTROL_HOST_OPERATIONS.len(),
        settings_window_operations: REQUIRED_NATIVE_SETTINGS_WINDOW_HOST_OPERATIONS.len(),
        settings_control_operations: REQUIRED_SETTINGS_CONTROL_HOST_OPERATIONS.len(),
        settings_dropdown_operations: REQUIRED_NATIVE_SETTINGS_DROPDOWN_HOST_OPERATIONS.len(),
        shared_non_host_protocols: SHARED_NON_HOST_UI_PROTOCOLS.len(),
        backend: LinuxNativeBackend::Gtk4Libadwaita,
    }
}
