use super::prelude::*;

pub(super) struct SettingsWndState {
    pub(super) parent_hwnd: HWND,
    pub(super) cur_page: usize,
    pub(super) ui_commands: CommandQueue,
    pub(super) ui_dpi: u32,
    pub(super) dpi_comp: DpiCompensationState,
    pub(super) nav_hot: i32,
    pub(super) content_scroll_y: i32,
    pub(super) page_scroll_y: [i32; SETTINGS_PAGE_COUNT],
    pub(super) scroll_dragging: bool,
    pub(super) scroll_drag_start_y: i32,
    pub(super) scroll_drag_start_scroll: i32,
    pub(super) scroll_bar_visible: bool,
    pub(super) scroll_hide_timer: bool,
    pub(super) save_hint_timer: bool,
    pub(super) ui: SettingsUiRegistry,
    pub(super) btn_save: HWND,
    pub(super) btn_close: HWND,
    pub(super) btn_open_cfg: HWND,
    pub(super) chk_autostart: HWND,
    pub(super) chk_silent_start: HWND,
    pub(super) chk_tray_icon: HWND,
    pub(super) chk_close_tray: HWND,
    pub(super) chk_click_hide: HWND,
    pub(super) chk_move_pasted_to_top: HWND,
    pub(super) chk_persistent_search: HWND,
    pub(super) chk_paste_sound: HWND,
    pub(super) cb_paste_sound: HWND,
    pub(super) btn_paste_sound_pick: HWND,
    pub(super) chk_skip_window: HWND,
    pub(super) ed_skip_class_names: HWND,
    pub(super) btn_capture_skip_window: HWND,
    pub(super) chk_auto_hide_on_blur: HWND,
    pub(super) chk_edge_hide: HWND,
    pub(super) chk_hover_preview: HWND,
    pub(super) chk_group_enable: HWND,
    pub(super) lb_group_current: HWND,
    pub(super) lb_groups: HWND,
    pub(super) btn_group_add: HWND,
    pub(super) btn_group_rename: HWND,
    pub(super) btn_group_delete: HWND,
    pub(super) btn_group_up: HWND,
    pub(super) btn_group_down: HWND,
    pub(super) record_groups_cache: Vec<ClipGroup>,
    pub(super) phrase_groups_cache: Vec<ClipGroup>,
    pub(super) chk_hk_enable: HWND,
    pub(super) cb_hk_mod: HWND,
    pub(super) cb_hk_key: HWND,
    pub(super) lb_hk_preview: HWND,
    pub(super) btn_hk_record: HWND,
    pub(super) chk_plain_hk_enable: HWND,
    pub(super) cb_plain_hk_mod: HWND,
    pub(super) cb_plain_hk_key: HWND,
    pub(super) lb_plain_hk_preview: HWND,
    pub(super) hotkey_recording: bool,
    pub(super) btn_clip_hist_block: HWND,
    pub(super) btn_clip_hist_restore: HWND,
    pub(super) btn_restart_explorer: HWND,
    pub(super) lb_qs_title: HWND,
    pub(super) chk_qs: HWND,
    pub(super) lb_qs_status: HWND,
    pub(super) lb_qs_engine: HWND,
    pub(super) cb_engine: HWND,
    pub(super) lb_qs_template: HWND,
    pub(super) ed_tpl: HWND,
    pub(super) btn_qs_restore: HWND,
    pub(super) lb_qs_hint: HWND,
    pub(super) lb_ocr_title: HWND,
    pub(super) cb_ocr_provider: HWND,
    pub(super) lb_ocr_primary: HWND,
    pub(super) ed_ocr_cloud_url: HWND,
    pub(super) lb_ocr_secondary: HWND,
    pub(super) ed_ocr_cloud_token: HWND,
    pub(super) lb_ocr_status: HWND,
    pub(super) btn_ocr_detect: HWND,
    pub(super) lb_translate_title: HWND,
    pub(super) cb_translate_provider: HWND,
    pub(super) lb_translate_status: HWND,
    pub(super) lb_translate_primary: HWND,
    pub(super) ed_translate_app_id: HWND,
    pub(super) lb_translate_secondary: HWND,
    pub(super) ed_translate_secret: HWND,
    pub(super) lb_translate_target: HWND,
    pub(super) cb_translate_target: HWND,
    pub(super) lb_ai_status: HWND,
    pub(super) lb_ai_title: HWND,
    pub(super) lb_mail_merge_title: HWND,
    pub(super) lb_mail_merge_status: HWND,
    pub(super) btn_mail_merge: HWND,
    pub(super) lb_wps_taskpane_title: HWND,
    pub(super) chk_wps_taskpane: HWND,
    pub(super) btn_wps_taskpane_docs: HWND,
    pub(super) lb_qr_title: HWND,
    pub(super) lb_qr_status: HWND,
    pub(super) cb_vv_source: HWND,
    pub(super) cb_vv_group: HWND,
    pub(super) vv_source_selected: usize,
    pub(super) vv_group_selected: i64,
    pub(super) group_view_tab: usize,
    pub(super) btn_group_view_records: HWND,
    pub(super) btn_group_view_phrases: HWND,
    pub(super) chk_ai: HWND,
    pub(super) chk_mm: HWND,
    pub(super) chk_qr: HWND,
    pub(super) cb_multi_sync_mode: HWND,
    pub(super) cb_cloud_interval: HWND,
    pub(super) lb_multi_sync_summary: HWND,
    pub(super) ed_cloud_url: HWND,
    pub(super) ed_cloud_user: HWND,
    pub(super) ed_cloud_pass: HWND,
    pub(super) ed_cloud_dir: HWND,
    pub(super) lb_cloud_status: HWND,
    pub(super) ed_lan_name: HWND,
    pub(super) ed_lan_tcp_port: HWND,
    pub(super) lb_lan_status: HWND,
    pub(super) cb_lan_receive_mode: HWND,
    pub(super) ed_lan_manual_host: HWND,
    pub(super) btn_lan_pair: HWND,
    pub(super) btn_lan_refresh: HWND,
    pub(super) btn_lan_docs: HWND,
    pub(super) qr_lan_android: HWND,
    pub(super) qr_lan_ios: HWND,
    pub(super) qr_lan_android_cache: Option<SettingsQrCache>,
    pub(super) qr_lan_ios_cache: Option<SettingsQrCache>,
    pub(super) btn_lan_copy_pair: HWND,
    pub(super) btn_lan_copy_setup: HWND,
    pub(super) lb_lan_devices: HWND,
    pub(super) lb_lan_trusted: HWND,
    pub(super) btn_lan_accept_pair: HWND,
    pub(super) btn_lan_reject_pair: HWND,
    pub(super) lan_discovered_cache: Vec<lan_sync::LanDevice>,
    pub(super) lan_pending_cache: Vec<lan_sync::LanPairPrompt>,
    pub(super) cb_max: HWND,
    pub(super) cb_pos: HWND,
    pub(super) ed_dx: HWND,
    pub(super) ed_dy: HWND,
    pub(super) ed_fx: HWND,
    pub(super) ed_fy: HWND,
    pub(super) btn_open_update: HWND,
    pub(super) nav_font: *mut core::ffi::c_void,
    pub(super) ui_font: *mut core::ffi::c_void,
    pub(super) title_font: *mut core::ffi::c_void,
    pub(super) draft: AppSettings,
    pub(super) ownerdraw_ctrls: Vec<HWND>,
    pub(super) hot_ownerdraw: HWND,
    pub(super) bg_brush: *mut core::ffi::c_void,
    pub(super) surface_brush: *mut core::ffi::c_void,
    pub(super) control_brush: *mut core::ffi::c_void,
    pub(super) nav_brush: *mut core::ffi::c_void,
    pub(super) dropdown_popup: HWND,
    pub(super) plugin_sections: Vec<SettingsSection>,
    pub(super) multi_sync_sections: Vec<SettingsSection>,
}

impl SettingsWndState {
    pub(super) fn new(
        parent_hwnd: HWND,
        ui_dpi: u32,
        nav_font: *mut core::ffi::c_void,
        ui_font: *mut core::ffi::c_void,
        title_font: *mut core::ffi::c_void,
    ) -> Self {
        Self {
            parent_hwnd,
            cur_page: 0,
            ui_commands: CommandQueue::default(),
            ui_dpi,
            dpi_comp: DpiCompensationState::default(),
            content_scroll_y: 0,
            page_scroll_y: [0; SETTINGS_PAGE_COUNT],
            scroll_dragging: false,
            scroll_drag_start_y: 0,
            scroll_drag_start_scroll: 0,
            scroll_bar_visible: false,
            scroll_hide_timer: false,
            save_hint_timer: false,
            ui: SettingsUiRegistry::new(),
            nav_hot: -1,
            btn_save: null_mut(),
            btn_close: null_mut(),
            btn_open_cfg: null_mut(),
            chk_autostart: null_mut(),
            chk_silent_start: null_mut(),
            chk_tray_icon: null_mut(),
            chk_close_tray: null_mut(),
            chk_click_hide: null_mut(),
            chk_move_pasted_to_top: null_mut(),
            chk_persistent_search: null_mut(),
            chk_paste_sound: null_mut(),
            cb_paste_sound: null_mut(),
            btn_paste_sound_pick: null_mut(),
            chk_skip_window: null_mut(),
            ed_skip_class_names: null_mut(),
            btn_capture_skip_window: null_mut(),
            chk_auto_hide_on_blur: null_mut(),
            chk_edge_hide: null_mut(),
            chk_hover_preview: null_mut(),
            chk_group_enable: null_mut(),
            lb_group_current: null_mut(),
            lb_groups: null_mut(),
            btn_group_add: null_mut(),
            btn_group_rename: null_mut(),
            btn_group_delete: null_mut(),
            btn_group_up: null_mut(),
            btn_group_down: null_mut(),
            record_groups_cache: Vec::new(),
            phrase_groups_cache: Vec::new(),
            chk_hk_enable: null_mut(),
            cb_hk_mod: null_mut(),
            cb_hk_key: null_mut(),
            lb_hk_preview: null_mut(),
            btn_hk_record: null_mut(),
            chk_plain_hk_enable: null_mut(),
            cb_plain_hk_mod: null_mut(),
            cb_plain_hk_key: null_mut(),
            lb_plain_hk_preview: null_mut(),
            hotkey_recording: false,
            btn_clip_hist_block: null_mut(),
            btn_clip_hist_restore: null_mut(),
            btn_restart_explorer: null_mut(),
            lb_qs_title: null_mut(),
            chk_qs: null_mut(),
            lb_qs_status: null_mut(),
            lb_qs_engine: null_mut(),
            cb_engine: null_mut(),
            lb_qs_template: null_mut(),
            ed_tpl: null_mut(),
            btn_qs_restore: null_mut(),
            lb_qs_hint: null_mut(),
            lb_ocr_title: null_mut(),
            cb_ocr_provider: null_mut(),
            lb_ocr_primary: null_mut(),
            ed_ocr_cloud_url: null_mut(),
            lb_ocr_secondary: null_mut(),
            ed_ocr_cloud_token: null_mut(),
            lb_ocr_status: null_mut(),
            btn_ocr_detect: null_mut(),
            lb_translate_title: null_mut(),
            cb_translate_provider: null_mut(),
            lb_translate_status: null_mut(),
            lb_translate_primary: null_mut(),
            ed_translate_app_id: null_mut(),
            lb_translate_secondary: null_mut(),
            ed_translate_secret: null_mut(),
            lb_translate_target: null_mut(),
            cb_translate_target: null_mut(),
            lb_ai_status: null_mut(),
            lb_ai_title: null_mut(),
            lb_mail_merge_title: null_mut(),
            lb_mail_merge_status: null_mut(),
            btn_mail_merge: null_mut(),
            lb_wps_taskpane_title: null_mut(),
            chk_wps_taskpane: null_mut(),
            btn_wps_taskpane_docs: null_mut(),
            lb_qr_title: null_mut(),
            lb_qr_status: null_mut(),
            cb_vv_source: null_mut(),
            cb_vv_group: null_mut(),
            vv_source_selected: 0,
            vv_group_selected: 0,
            group_view_tab: 0,
            btn_group_view_records: null_mut(),
            btn_group_view_phrases: null_mut(),
            chk_ai: null_mut(),
            chk_mm: null_mut(),
            chk_qr: null_mut(),
            cb_multi_sync_mode: null_mut(),
            cb_cloud_interval: null_mut(),
            lb_multi_sync_summary: null_mut(),
            ed_cloud_url: null_mut(),
            ed_cloud_user: null_mut(),
            ed_cloud_pass: null_mut(),
            ed_cloud_dir: null_mut(),
            lb_cloud_status: null_mut(),
            ed_lan_name: null_mut(),
            ed_lan_tcp_port: null_mut(),
            lb_lan_status: null_mut(),
            cb_lan_receive_mode: null_mut(),
            ed_lan_manual_host: null_mut(),
            btn_lan_pair: null_mut(),
            btn_lan_refresh: null_mut(),
            btn_lan_docs: null_mut(),
            qr_lan_android: null_mut(),
            qr_lan_ios: null_mut(),
            qr_lan_android_cache: None,
            qr_lan_ios_cache: None,
            btn_lan_copy_pair: null_mut(),
            btn_lan_copy_setup: null_mut(),
            lb_lan_devices: null_mut(),
            lb_lan_trusted: null_mut(),
            btn_lan_accept_pair: null_mut(),
            btn_lan_reject_pair: null_mut(),
            lan_discovered_cache: Vec::new(),
            lan_pending_cache: Vec::new(),
            cb_max: null_mut(),
            cb_pos: null_mut(),
            ed_dx: null_mut(),
            ed_dy: null_mut(),
            ed_fx: null_mut(),
            ed_fy: null_mut(),
            btn_open_update: null_mut(),
            nav_font,
            ui_font,
            title_font,
            draft: AppSettings::default(),
            ownerdraw_ctrls: Vec::new(),
            hot_ownerdraw: null_mut(),
            bg_brush: null_mut(),
            surface_brush: null_mut(),
            control_brush: null_mut(),
            nav_brush: null_mut(),
            dropdown_popup: null_mut(),
            plugin_sections: crate::settings_model::settings_plugin_cards_for_state(
                false, "off", "off", false, false,
            ),
            multi_sync_sections: crate::settings_model::settings_multi_sync_cards_for_mode("off"),
        }
    }
}
