mod constants;
pub(crate) mod data;
mod main_clipboard_capture;
mod main_cloud_sync;
mod main_edge_auto_hide;
mod main_entry;
mod main_events;
mod main_hover_preview;
mod main_input;
mod main_lan_sync;
mod main_low_level_input;
mod main_paste;
mod main_paste_target_discovery;
mod main_platform_bindings;
mod main_popup_menus;
mod main_renderer;
mod main_row_commands;
mod main_row_tools;
mod main_search;
mod main_search_host;
mod main_startup_integrations;
mod main_view_helpers;
mod main_window;
mod main_window_host;
mod main_window_refresh;
mod main_window_registry;
mod platform_helpers;
mod prelude;
pub(crate) mod runtime;
mod settings_about_page;
mod settings_about_page_data;
mod settings_about_page_metadata;
mod settings_about_page_update;
mod settings_actions;
mod settings_app_apply;
mod settings_app_collect;
mod settings_app_collect_cloud;
mod settings_app_collect_general;
mod settings_app_collect_group;
mod settings_app_collect_hotkey;
mod settings_app_collect_plugin;
mod settings_app_data_effects;
mod settings_app_effect_state;
mod settings_app_effects;
mod settings_app_integration_effects;
mod settings_app_window_effects;
mod settings_cloud_page;
mod settings_cloud_page_lan;
mod settings_cloud_page_lan_devices;
mod settings_cloud_page_webdav;
mod settings_command_queue;
mod settings_control_factory;
mod settings_control_registry;
mod settings_control_selection;
mod settings_control_selection_cloud;
mod settings_control_selection_general;
mod settings_control_selection_group;
mod settings_control_selection_hotkey;
mod settings_control_selection_plugin;
mod settings_dropdown;
mod settings_dropdown_cloud;
mod settings_dropdown_general;
mod settings_dropdown_group;
mod settings_dropdown_host;
mod settings_dropdown_hotkey;
mod settings_dropdown_plugin;
mod settings_form_actions;
mod settings_form_fields;
mod settings_general_page;
mod settings_general_page_startup;
mod settings_general_page_window;
mod settings_group_actions;
mod settings_group_page;
mod settings_group_sections;
mod settings_group_sections_cache;
mod settings_group_sections_display;
mod settings_group_sections_list;
mod settings_host_helpers;
mod settings_hotkey_page;
mod settings_hotkey_page_shortcuts;
mod settings_hotkey_page_system;
mod settings_input;
mod settings_keyboard_input;
mod settings_multi_sync_sections;
mod settings_owner_draw;
mod settings_owner_draw_link;
mod settings_owner_draw_qr;
mod settings_owner_draw_roles;
mod settings_page_builder;
mod settings_page_ensure;
mod settings_page_navigation;
mod settings_page_navigation_controls;
mod settings_page_navigation_scroll;
mod settings_page_navigation_switch;
mod settings_page_sync;
mod settings_page_sync_cloud;
mod settings_page_sync_cloud_lan;
mod settings_page_sync_cloud_webdav;
mod settings_page_sync_plugin;
mod settings_platform_actions;
mod settings_platform_actions_about;
mod settings_platform_actions_general;
mod settings_platform_actions_hotkey;
mod settings_platform_actions_plugin;
mod settings_platform_actions_system;
mod settings_plugin_page;
mod settings_plugin_page_ocr_translate;
mod settings_plugin_page_search;
mod settings_plugin_page_tools;
mod settings_plugin_sections;
mod settings_plugin_sections_controls;
mod settings_plugin_sections_layout;
mod settings_plugin_sections_providers;
mod settings_plugin_sections_tools;
mod settings_pointer_input;
mod settings_raw_controls;
mod settings_state;
mod settings_sync_actions;
mod settings_sync_actions_lan;
mod settings_sync_actions_webdav;
mod settings_timer_tasks;
mod settings_toggle_state;
mod settings_toggle_state_cloud;
mod settings_toggle_state_general;
mod settings_toggle_state_group;
mod settings_toggle_state_hotkey;
mod settings_toggle_state_plugin;
mod settings_window;
mod settings_window_colors;
mod settings_window_create;
mod settings_window_destroy;
mod settings_window_events;
mod settings_window_layout;
mod settings_window_lifecycle;
mod settings_window_metrics;
mod settings_window_owner_draw;
mod settings_window_paint;
mod settings_window_surface_controls;
pub(crate) mod state;
mod state_runtime;
mod transient_window_host;
mod vv_hook;
mod vv_popup;
mod windows_messages;

pub(crate) use self::constants::TRAY_UID;
pub(crate) use self::data::{ensure_item_image_bytes, rich_text_preview_text};
pub(crate) use self::main_edge_auto_hide::{
    clear_edge_dock_state, note_window_moved_for_edge_hide, try_restore_edge_hidden_window,
};
pub(crate) use self::main_entry::run;
pub(crate) use self::main_low_level_input::refresh_low_level_input_hooks;
pub(crate) use self::main_row_tools::image_input_for_ocr;
pub(crate) use self::main_search::{layout_children, reset_search_ui_state};
pub(crate) use self::main_window::{
    hide_main_window, present_main_window, refresh_main_window_layout_for_monitor,
    set_main_window_activation_policy, set_main_window_bounds,
};
pub(crate) use self::main_window_refresh::refresh_window_for_show;
pub(crate) use self::main_window_registry::{get_state_ptr, quick_window_hwnd};
pub(crate) use self::prelude::{ClipItem, ClipKind};
pub(crate) use self::runtime::{data_dir, save_settings};
pub(crate) use self::state::{AppState, Icons};
pub(crate) use self::windows_messages::{WM_LAN_SYNC_READY, WM_TRAYICON};

#[cfg(test)]
#[path = "app_tests.rs"]
mod tests;
