﻿;[KEYBOARD_SWITCH] 设置类型
;type=设置项显示类型0-文字icon+文字；1-图片iocn+文字 2-图片icon
;style=style属性名
;status=点击状态0-弹出面板 1-状态切换 2-页面跳转
;order_inToolbar=当前设置项在工具栏上的位置
;order=在当前列表里的位置

;[KEYBOARD_SWITCH_TEXT]
;typeface=字体；默认为Qicon
;icon_char=字体包里对应的index
;icon_size=字体大小
;text=设置项对应的文字提示
;new_tip=右上角标记,0-无标记,1-new标记,2-红点标记,3-有new和红点标记,new优先展示
;icon_name=图片类型，图片名

;第一个版本先支持目前的 type=0；保留扩展的可能性

;设置面板通用配置
[SETTINGS_BOARD_COMMON_STYLE]
;typeface=
icon_color=0xff000000
text_color=0xff000000

icon_color_press=0xff000000
text_color_press=0xff000000
item_bg_color_press=0xffededed

;title_color=
;sub_title_color=
activity_detail_bg_normal=0xffffffff
activity_detail_bg_press=0xffededed
activity_close_normal=0xff000000
activity_close_press=0xff000000

;所有面板通用配置
[COMMON_STYLE]
board_bg_color=0xffffffff
first_candi_color=0xff000000
second_candi_color=0xff000000
divider_line_color=0xffe3e3e3
page_index_normal=
page_index_selected=

;键盘切换
[KEYBOARD_SWITCH]
type=0
text=键盘切换
icon_name=switch_board_icon.png
status=0
order=11
id=2
new_tip=0
;order_inToolbar=

;常用语
[PHRASE_BOARD]
type=0
text=常用语
icon_name=phrase_board_icon.png
status=0
order=13
id=3
new_tip=0

;输入编辑
[UTILITY_BOARD]
type=0
text=输入编辑
icon_name=utility_board_icon.png
status=0
order=2
id=4
new_tip=0

;皮肤
[SKIN_SWITCH]
type=0
text=皮肤
icon_name=skin_switch_board_icon.png
status=0
order=1
id=6
new_tip=0

;字体
[CAND_FONTS]
type=0
text=字体
icon_name=cand_font_icon.png
status=0
order=19
id=14
new_tip=0

;表情
[EXPRESSION_BOARD]
type=0
text=表情
icon_name=expression_board_icon.png
status=0
order=10
id=13
new_tip=0

;词库
[WORD_DICT]
type=0
text=词库
icon_name=word_dict_icon.png
status=2
order=21
id=8
new_tip=0

;简繁切换
[TRA2SIM_BOARD]
type=0
text=简繁切换
icon_name=tran2sim_sim_icon.png,tran2sim_tran_icon.png
status=1
order=14
id=7
new_tip=0

;键盘大小
[KEYBOARD_HEIGHT]
type=0
text=键盘大小
icon_name=keyboard_size_icon.png
status=1
order=17
id=11
new_tip=0

;音效设置
[SOUND_BOARD]
type=0
text=音效设置
icon_name=sound_board_icon.png
status=0
order=18
id=12
new_tip=0

;剪贴板
[CLIP_BOARD]
type=0
text=剪贴板
icon_name=clip_board_icon.png
status=0
order=4
id=16
new_tip=0

;浮动键盘
[SINGLE_HAND_MODE]
type=0
text=浮动键盘
icon_name=float_keyboard_on_icon.png,float_keyboard_off_icon.png
status=1
order=16
id=10
new_tip=0

;更多设置
[MORE_SETTING_BOARD]
type=0
text=更多设置
icon_name=more_setting_board_icon.png
status=2
order=23
id=9
new_tip=0

;自定义工具栏
;[ADJUST_TOOL_BAR]
;type=0
;style=ADJUST_TOOL_BAR_STYLE
;status=2
;order=13
;id=17
;new_tip=0
;[ADJUST_TOOL_BAR_STYLE]
;icon_char=0xEE92
;text=自定义工具栏
;icon_name=


;花式语音
[ONLINE_VOICE_BOARD]
type=0
text=花式语音
icon_name=voice_board_icon.png
status=2
order=12
id=5
new_tip=2

;夜间模式
[NIGHT_MODE]
type=0
text=夜间模式
icon_name=night_mode_off_icon.png,night_mode_on_icon.png
status=1
order=20
id=18
new_tip=0


[KEYBOARD_HW]
type=0
text=键盘手写
icon_name=keyboard_hw_on_icon.png,keyboard_hw_off_icon.png
status=2
order=15
id=15
new_tip=0


[KEYBOARD_WANGZHE]
type=0
text=王者键盘
icon_name=wangzhe_board_icon.png
status=0
order=22
id=19
new_tip=0


;快捷翻译
[QUICK_TRANSLATE]
type=0
text=快捷翻译
icon_name=translate_off_icon.png,translate_on_icon.png
status=1
order=5
id=20
new_tip=0

;聊天气泡
[CHAT_BUBBLE]
type=0
text=聊天气泡
icon_name=chat_bubble.png
status=0
order=8
id=25
new_tip=2

;神配图
[CRAZY_DOUTU]
type=0
status=1
order=7
id=24
new_tip=0
text=神配图
icon_name=crazy_doutu_on_icon.png,crazy_doutu_off_icon.png

;闪电萌语
[QUICK_PHRASE]
type=0
text=闪电萌语
icon_name=quick_phrase_icon.png
status=0
order=3
id=21
new_tip=2

;神人趣聊
[EMOJI_MODE]
type=0
text=神人趣聊
icon_name=emoji_mode.png
status=0
order=6
id=27
new_tip=0

;魔音
[MAGIC_VOICE]
type=0
status=1
order=9
id=28
new_tip=1
text=魔音
icon_name=magic_voice_on_icon.png,magic_voice_off_icon.png